global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fitos-backend'
    static_configs:
      - targets: ['fitos-app:3001']
    metrics_path: '/api/metrics'
    scrape_interval: 5s

  - job_name: 'fitos-frontend'
    static_configs:
      - targets: ['fitos-app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']

  - job_name: 'chroma'
    static_configs:
      - targets: ['chroma:8000']

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
